# Generated by Django 5.2.1 on 2025-06-07 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('user', 'name'), ('user', 'slug')},
        ),
    ]
