# Generated by Django 5.2.1 on 2025-06-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_name_alter_link_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
